version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-ecommerce
    volumes:
      - ./src:/var/www/html
    ports:
      - 8000:8000
    environment:
      - APP_ENV=local
    networks:
      - ecommerce-network
    depends_on:
      - db
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mysql:8.0
    container_name: ecommerce-db
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
